# Generated by Django 4.0.3 on 2022-03-31 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='text',
            field=models.CharField(default='', max_length=1000, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
