# Generated by Django 4.0.3 on 2022-04-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientamount',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Список ингредиентов'},
        ),
    ]
