# Generated by Django 4.0.3 on 2022-03-30 14:51

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='unique_follow',
        ),
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='check_self_follow',
        ),
        migrations.RenameField(
            model_name='subscribe',
            old_name='to_user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='subscribe',
            old_name='from_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscribers',
        ),
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_follow'),
        ),
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.CheckConstraint(check=models.Q(('user', django.db.models.expressions.F('author')), _negated=True), name='check_self_follow'),
        ),
    ]
